### ISSUE TITLE
Ability cooldowns discontinued? takes several minutes to load the in-game draw.

### ISSUE THREAD

**Issue by T9es** [vakdev/VakScript#12]
Is this discontinued? I noticed the new version missing that cooldown option, even though the settings still have it.

Also, I've experienced several issues with the new patch trying to run it with the game. Even in admin mode, it takes several minutes to load the draws onto the game. (No longer an issue, managed to fix this myself.)

The old version does work with spells, telling what the enemy upgraded, although the cooldowns don't show at all. Haven't really ran through the code, but is there anything that needs to be updated/changed for this to work? (Like some offsets being present in some OTHER file than data), or did I just mess up at the offsets level?

Edit: Also now seem to encounter the UI turn the whole screen black.

**Comment by vakdev** [comment]
Updated, try new version.

**Comment by T9es** [comment]
Ability cooldowns still aren't showing, only the skills taken. Summoner spells are also removed?
