### ISSUE TITLE
Sometimes it just cancels auto attacks a lot of times in a row, same when last hitting minions or wave clearing.

### ISSUE THREAD

**Issue by blackBusterH** [vakdev/VakScript#15]
While holding space for champions or clearing minions with it, it can sometimes cancel auto attacks completely is there any fix for this?

**Comment by Wonpil-Myoui** [comment]
Hi, how do you get it to work ingame? I checked autoconfig>reconnected. Ticked space glider but pressing any keys ingame doesnt do anything

**Comment by vakdev** [comment]
Windup formula updated, try latest version.
