### ISSUE TITLE
Just kills league

### ISSUE THREAD

**Issue by AlizerUncaged** [vakdev/VakScript#3]
whenever I run main.py it just kills league if I try to open a game
![image](https://github.com/vakdev/VakScript/assets/86959368/7f907870-a5df-4d28-9937-a5a8332b09df)

**Comment by vakdev** [comment]
Disable Autoconfig in GUI or in settings.json

**Comment by vakdev** [comment]
> whenever I run main.py it just kills league if I try to open a game ![image](https://user-images.githubusercontent.com/86959368/241394057-7f907870-a5df-4d28-9937-a5a8332b09df.png)

Disable Autoconfig in GUI or in settings.json
